### PR TITLE
Make HTTP header variables constant and set

### PR DESCRIPTION
**Pull request by hlcfan**
+ Make HTTP header variables constant
+ Set is much faster when calling `#include?`

### CODE REVIEW

**Comment by adamzaninovich** [comment]
This looks good. I would make one more change:
```ruby
env.keys.select! do |key|
  DEFAULT_VARIABLES.include?(key) || key.include?("rack")
end
```
might be easier to read.

**Comment by adamzaninovich** [comment]
Looks great! 👍

**Comment by adamzaninovich** [comment]
@NateBarnes ready to merge as far as I'm concerned

**Comment by NateBarnes** [comment]
I'll Allow It

**Pull request merged**
